[spark]
appname=MyETLJob
master=local[*]
env=dev
targetstorage=file
targetfilepath=/tmp/input.csv
loadMethod=full
ispartitioned=true
partitioncolumnlist=country,year
jars=

[kafka]
insertintokafka=false
