[SPARK_CONTEXT]
spark.app.name=MyETLJob
spark.master=local[*]
spark.jars=/opt/spark/jars/postgresql-42.2.jar

[spark]
env=dev
targetstorage=file
targetfilepath=/tmp/input.csv
loadMethod=full
ispartitioned=true
partitioncolumnlist=country,year

[kafka]
insertintokafka=false
